wandb:
  project: "2025_icassp"
  # name: "${feature.sample_rate}-${feature.audio_feature}-${exp.model_name}-class${feature.dynamic_classes}-sec${feature.segment_seconds}-fft${feature.fft_size}-fps${feature.frames_per_second}-lr${exp.learning_rate}"
  name: "${wandb.note}-${feature.audio_feature}-${exp.model_name}-${exp.targets}-fold${dataset.fold_index}"
  note: "ablation" # or "formal"

exp:
  # workspace: "./workspaces"
  workspace: "/media/datadisk/home/22828187/zhanh/202505_dynest_data/workspaces"
  # workspace: "/media/mengh/SharedData/zhanh/202505_dynest_data/workspaces"
  random_seed: 86
  num_workers: 6
  cuda: true
  batch_size: 10
  mini_data: False

  # === Epoch-based training ===
  total_epochs: 36 #2          # total training epochs
  resume_epoch: 0               # resume from epoch checkpoint (epoch_N.pth)
  eval_epoch_interval: 8        # run evaluation every N epochs in train stage
  eval_batches: 20              # number of mini-batches per eval in the train stage
  log_interval_steps: 0         # 0 disables periodic loss/grad prints; >0 prints every N steps
  reduce_epoch: 2               # LR decay every N epochs (0 disables)
  use_adamw: True               # False to use Adam, True to use AdamW
  learning_rate: 3e-4           #2e-3 #1e-4
  decay: True
  input_type: "audio"           # "audio", "midi", "both" - sheetmusic handler entrance
  model_name: "MultiTaskCNN"    # "SingleCNN"
  targets: ["dynamic","change_point","beat","downbeat"] # default multitask CNN, ["dynamic"] or ["beat"] for SingleCNN

  # ===== Binary head loss & imbalance handling =====
  dynamic_mask: "beat"                    # beat-wise is in principle, optional development of downbeat, measure, change_point wise.
  dynamic_loss: "ce_dynamic"              # "ce" or "mse" or "mae"  
  beat_loss: "shift_tolerant_bce"         # "bce" | "shift_tolerant_bce" | "splitted_shift_tolerant_bce"
  downbeat_loss: "shift_tolerant_bce"     # same options as beat_loss; default to shift-tolerant
  change_point_loss: "shift_tolerant_bce" # same as above
  widen_target_mask: 3                    # ±frames used in loss tolerance and dataset pos_weight estimate
  use_dataset_pos_weight: true            # true: compute dataset-level pos_weight using widen; false: per-batch
  auto_scan_threshold: false              # true = auto-scan thresholds; false = use fixed "beat/downbeat/change_point" thresholds


feature:
  audio_feature: "sone"             # logmel (128 bins) or sone (24 bins)
  midi_feature:  "masked_velocity"  # "mask_velocity" or "velocity" - for the sheetmusic handler, not for model train/test
  dynamic_classes: 5                # 5-level (mazurka) or 8-level (real-world) mapping
  # === dataloader.py audio segmentation parameters ===
  segment_seconds: 60 #120.0        # Segment duration in seconds
  segment_hop_seconds: 30 #60.0     # Segment slicing step size in seconds, must equal or smaller than segment_seconds
  # === feature_extractor.py parameters ===
  sample_rate: 22050                # Audio sampling rate in Hz
  fft_size: 1024                    # FFT size for STFT (fft window length)
  frames_per_second: 50             # Determine the hop size for STFT (define fft window overlap ratio)
  augmentor: null                   # === Optional augmentation for waveform


cnn:
  latent_dim: 8
  fc_dropout: 0.2
  temporal_scale: [5,5]             # use [5,5] for proposed multitask CNN; use [3,3] reproduce original ICASSP2023 Single-task CNN, but worse performance

# ==== 新增结构开关 ====
  use_mmoe: true
  n_experts: 8
  export_mmoe_heatmap: false        # 导出 MMoE 专家门控热力图（inference 阶段生效）


dataset:
  use_5fold: True                   # Enable 5-fold CV; if run_all_folds=true this is forced to True
  run_all_folds: False              # True: sequentially train folds 0..4 in one run (forces use_5fold=True; ignores fold_index & random_split_ratio)
  fold_index: 0                     # Only used when run_all_folds=false and use_5fold=true; valid range: 0..4
  random_split_ratio: [8,1,1]       # Only used when use_5fold=false and run_all_folds=false (random train:valid:test split)
  mazurka:
    raw_meta_dir: "../202505_dynest_data/Dataset/MazurkaBL-master"
    cln_meta_dir: "../202505_dynest_data/Dataset/mazurka_meta"
    audio_dir:    "../202505_dynest_data/Dataset/mazurka_audio"
    midi_dir:     "../202505_dynest_data/Dataset/mazurka_mid"
    # Some opus included non-dynamic markings, hence excluded
    exclude_opus:
      - "M06-4"
      - "M63-2"
    # Some pids' annotations are not reliable (High Gradient in training), hence excluded
    # Use "null" to disable this during the evaluation process.
    exclude_pids: null
      # - "mazurka17-4/pid9058-13.h5"   # 3
      # - "mazurka33-4/pid9080-08.h5"   # 3
      # - "mazurka17-4/pid9173-18.h5"   # 2
      # - "mazurka56-3/pid9063b-10.h5"  # 2
      # - "mazurka50-3/pid9085-05.h5"   # 2
      # - "mazurka33-4/pid9068-15.h5"   # 1
      # - "mazurka33-4/pid9125-13.h5"   # 1
      # - "mazurka33-4/pid9057f-02.h5"  # 1
      # - "mazurka17-4/pid9161-12.h5"   # 1
      # - "mazurka17-4/pid9050-13.h5"   # 1
      # - "mazurka17-4/pid9170-13.h5"   # 1
